version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your-secret-key-change-this-in-production
      - DEBUG=False
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped

  # Optional: PostgreSQL database for production
  # Uncomment the following services if you want to use PostgreSQL instead of SQLite
  
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_DB: image_generator
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   restart: unless-stopped

  # web-with-postgres:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DJANGO_SECRET_KEY=your-secret-key-change-this-in-production
  #     - DEBUG=False
  #     - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/image_generator
  #   volumes:
  #     - ./staticfiles:/app/staticfiles
  #   restart: unless-stopped

# volumes:
#   postgres_data: