[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=5.2.5",
    "pillow>=11.3.0",
    "python-decouple>=3.8",
    "requests>=2.32.4",
]
