# Generated by Django 5.2.5 on 2025-08-08 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Text description used to generate the image')),
                ('image_url', models.URLField(help_text='URL of the generated image', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the image was generated')),
            ],
            options={
                'verbose_name': 'Generated Image',
                'verbose_name_plural': 'Generated Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
